import { Entity, Column, Index } from 'typeorm'

import { BaseTypeOrmModel } from '@dooform-api-core/infrastructure/persistence/typeorm'

/**
 * Per-tier feature configuration. One row per subscription tier (free / pro / max,
 * plus any custom tiers an admin adds). Replaces hardcoded `if (tier === FREE)`
 * checks scattered through the codebase — feature flags now live in the database
 * and are toggleable from the Tier admin console.
 */
@Entity('tier_configs')
@Index('uniq_tier_configs_code', ['code'], { unique: true })
export class TierConfigModel extends BaseTypeOrmModel {
  // Stable machine identifier — matches the `userTier` value persisted on users.
  @Column({ type: 'varchar', length: 32 })
  code!: string

  @Column({ type: 'varchar', length: 100 })
  label!: string

  @Column({ type: 'text', nullable: true })
  description!: string | null

  // Should documents generated by users on this tier carry the platform branding
  // watermark? Default: true for `free`, false for paid tiers.
  @Column({ name: 'apply_branding_watermark', type: 'boolean', default: false })
  applyBrandingWatermark!: boolean

  // Reserved for future tier capability flags. Free-form JSON so new feature toggles
  // can be added without schema migrations.
  @Column({ type: 'jsonb', nullable: true })
  features!: Record<string, unknown> | null

  @Column({ name: 'sort_order', type: 'int', default: 100 })
  sortOrder!: number

  @Column({ type: 'boolean', default: true })
  enabled!: boolean
}
